yaourt -S core/mhwd-nvidia
yaourt -S core/mhwd-nvidia-304xx
yaourt -S core/mhwd-nvidia-340xx
yaourt -S core/mhwd-nvidia-390xx
yaourt -S extra/libvdpau
yaourt -S extra/libxnvctrl
#yaourt -S extra/linux416-nvidia
yaourt -S extra/linux417-nvidia
yaourt -S extra/nvidia-utils
yaourt -S extra/opencl-nvidia
yaourt -S community/bumblebee
yaourt -S community/cuda
yaourt -S multilib/lib32-libvdpau
yaourt -S multilib/lib32-nvidia-utils
yaourt -S aur/nvdock-bumblebee
yaourt -S aur/nvidia-bumblebee-applet
yaourt -S aur/xgraphic
