
yay -S  --noconfirm core/mhwd-nvidia
yay -S  --noconfirm extra/libvdpau
yay -S  --noconfirm extra/libxnvctrl
yay -S  --noconfirm extra/linux52-nvidia
yay -S  --noconfirm extra/linux52-bbswitch
#yay -S  --noconfirm extra/linux52-nvidia-340xx
#yay -S  --noconfirm extra/linux52-nvidia-390xx
yay -S  --noconfirm extra/linux52-nvidia
yay -S  --noconfirm extra/nvidia-utils
yay -S  --noconfirm extra/opencl-nvidia
yay -S  --noconfirm bumblebee
yay -S  --noconfirm extra/linux52-bbswitch
yay -S  --noconfirm multilib/lib32-libvdpau
yay -S  --noconfirm multilib/lib32-nvidia-utils
yay -S  --noconfirm aur/nvdock-bumblebee
yay -S  --noconfirm aur/nvidia-bumblebee-applet
yay -S  --noconfirm aur/xgraphic
yay -S  --noconfirm aur/nvtop
yay -S  --noconfirm nvidia-xrun
#yay -S  --noconfirm community/cuda
