yaourt -S core/mhwd-nvidia
yaourt -S extra/libvdpau
yaourt -S extra/libxnvctrl
yaourt -S extra/linux51-nvidia
yaourt -S extra/linux51-bbswitch
yaourt -S extra/linux51-nvidia-340xx
yaourt -S extra/linux51-nvidia-390xx
yaourt -S extra/linux51-nvidia
yaourt -S extra/nvidia-utils
yaourt -S extra/opencl-nvidia
yaourt -S bumblebee
yaourt -S extra/linux51-bbswitch
#yaourt -S community/cuda
yaourt -S multilib/lib32-libvdpau
yaourt -S multilib/lib32-nvidia-utils
yaourt -S aur/nvdock-bumblebee
yaourt -S aur/nvidia-bumblebee-applet
yaourt -S aur/xgraphic
yaourt -S aur/nvtop
